version: "3.7"
services:
  geth:
    build:
      context: "../geth"
    command: "${GETH_ARGS}"
    ports:
      - "8545:8545"
      - "8546:8546"
    expose:
      - "8545"
      - "8546"
  ipfs:
    image: "ipfs/go-ipfs:release"
    volumes: 
      - type: "volume"
        source: "ipfs_staging"
        target: "/export"
      - type: "volume"
        source: "ipfs_data"
        target: "/data/ipfs"
    ports:
      - "127.0.0.1:4001:4001"
      - "127.0.0.1:4002:4002/udp"
      - "127.0.0.1:8081:8080"
      - "127.0.0.1:5001:5001"
    expose:
      - "4001"
      - "4002"
      - "8080"
      - "5001"
volumes:
  ipfs_staging:
  ipfs_data:
